/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TradeService } from "../trade.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TradeCreateInput } from "./TradeCreateInput";
import { Trade } from "./Trade";
import { TradeFindManyArgs } from "./TradeFindManyArgs";
import { TradeWhereUniqueInput } from "./TradeWhereUniqueInput";
import { TradeUpdateInput } from "./TradeUpdateInput";
import { BotScheduleFindManyArgs } from "../../botSchedule/base/BotScheduleFindManyArgs";
import { BotSchedule } from "../../botSchedule/base/BotSchedule";
import { BotScheduleWhereUniqueInput } from "../../botSchedule/base/BotScheduleWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TradeControllerBase {
  constructor(
    protected readonly service: TradeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Trade })
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTrade(@common.Body() data: TradeCreateInput): Promise<Trade> {
    return await this.service.createTrade({
      data: {
        ...data,

        token: data.token
          ? {
              connect: data.token,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        duration: true,
        numberOfTrades: true,
        amount: true,

        token: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Trade] })
  @ApiNestedQuery(TradeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async trades(@common.Req() request: Request): Promise<Trade[]> {
    const args = plainToClass(TradeFindManyArgs, request.query);
    return this.service.trades({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        duration: true,
        numberOfTrades: true,
        amount: true,

        token: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Trade })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async trade(
    @common.Param() params: TradeWhereUniqueInput
  ): Promise<Trade | null> {
    const result = await this.service.trade({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        duration: true,
        numberOfTrades: true,
        amount: true,

        token: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Trade })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTrade(
    @common.Param() params: TradeWhereUniqueInput,
    @common.Body() data: TradeUpdateInput
  ): Promise<Trade | null> {
    try {
      return await this.service.updateTrade({
        where: params,
        data: {
          ...data,

          token: data.token
            ? {
                connect: data.token,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          duration: true,
          numberOfTrades: true,
          amount: true,

          token: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Trade })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTrade(
    @common.Param() params: TradeWhereUniqueInput
  ): Promise<Trade | null> {
    try {
      return await this.service.deleteTrade({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          duration: true,
          numberOfTrades: true,
          amount: true,

          token: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/botSchedules")
  @ApiNestedQuery(BotScheduleFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "BotSchedule",
    action: "read",
    possession: "any",
  })
  async findBotSchedules(
    @common.Req() request: Request,
    @common.Param() params: TradeWhereUniqueInput
  ): Promise<BotSchedule[]> {
    const query = plainToClass(BotScheduleFindManyArgs, request.query);
    const results = await this.service.findBotSchedules(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,
        runAt: true,

        trade: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/botSchedules")
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "update",
    possession: "any",
  })
  async connectBotSchedules(
    @common.Param() params: TradeWhereUniqueInput,
    @common.Body() body: BotScheduleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      botSchedules: {
        connect: body,
      },
    };
    await this.service.updateTrade({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/botSchedules")
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "update",
    possession: "any",
  })
  async updateBotSchedules(
    @common.Param() params: TradeWhereUniqueInput,
    @common.Body() body: BotScheduleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      botSchedules: {
        set: body,
      },
    };
    await this.service.updateTrade({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/botSchedules")
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "update",
    possession: "any",
  })
  async disconnectBotSchedules(
    @common.Param() params: TradeWhereUniqueInput,
    @common.Body() body: BotScheduleWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      botSchedules: {
        disconnect: body,
      },
    };
    await this.service.updateTrade({
      where: params,
      data,
      select: { id: true },
    });
  }
}
