/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Trade } from "./Trade";
import { TradeCountArgs } from "./TradeCountArgs";
import { TradeFindManyArgs } from "./TradeFindManyArgs";
import { TradeFindUniqueArgs } from "./TradeFindUniqueArgs";
import { CreateTradeArgs } from "./CreateTradeArgs";
import { UpdateTradeArgs } from "./UpdateTradeArgs";
import { DeleteTradeArgs } from "./DeleteTradeArgs";
import { BotScheduleFindManyArgs } from "../../botSchedule/base/BotScheduleFindManyArgs";
import { BotSchedule } from "../../botSchedule/base/BotSchedule";
import { Token } from "../../token/base/Token";
import { TradeService } from "../trade.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Trade)
export class TradeResolverBase {
  constructor(
    protected readonly service: TradeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "read",
    possession: "any",
  })
  async _tradesMeta(
    @graphql.Args() args: TradeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Trade])
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "read",
    possession: "any",
  })
  async trades(@graphql.Args() args: TradeFindManyArgs): Promise<Trade[]> {
    return this.service.trades(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Trade, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "read",
    possession: "own",
  })
  async trade(
    @graphql.Args() args: TradeFindUniqueArgs
  ): Promise<Trade | null> {
    const result = await this.service.trade(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Trade)
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "create",
    possession: "any",
  })
  async createTrade(@graphql.Args() args: CreateTradeArgs): Promise<Trade> {
    return await this.service.createTrade({
      ...args,
      data: {
        ...args.data,

        token: args.data.token
          ? {
              connect: args.data.token,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Trade)
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "update",
    possession: "any",
  })
  async updateTrade(
    @graphql.Args() args: UpdateTradeArgs
  ): Promise<Trade | null> {
    try {
      return await this.service.updateTrade({
        ...args,
        data: {
          ...args.data,

          token: args.data.token
            ? {
                connect: args.data.token,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Trade)
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "delete",
    possession: "any",
  })
  async deleteTrade(
    @graphql.Args() args: DeleteTradeArgs
  ): Promise<Trade | null> {
    try {
      return await this.service.deleteTrade(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [BotSchedule], { name: "botSchedules" })
  @nestAccessControl.UseRoles({
    resource: "BotSchedule",
    action: "read",
    possession: "any",
  })
  async findBotSchedules(
    @graphql.Parent() parent: Trade,
    @graphql.Args() args: BotScheduleFindManyArgs
  ): Promise<BotSchedule[]> {
    const results = await this.service.findBotSchedules(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Token, {
    nullable: true,
    name: "token",
  })
  @nestAccessControl.UseRoles({
    resource: "Token",
    action: "read",
    possession: "any",
  })
  async getToken(@graphql.Parent() parent: Trade): Promise<Token | null> {
    const result = await this.service.getToken(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
