/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { BotScheduleListRelationFilter } from "../../botSchedule/base/BotScheduleListRelationFilter";
import { TokenWhereUniqueInput } from "../../token/base/TokenWhereUniqueInput";

@InputType()
class TradeWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  duration?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  numberOfTrades?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  amount?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: () => BotScheduleListRelationFilter,
  })
  @ValidateNested()
  @Type(() => BotScheduleListRelationFilter)
  @IsOptional()
  @Field(() => BotScheduleListRelationFilter, {
    nullable: true,
  })
  botSchedules?: BotScheduleListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => TokenWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TokenWhereUniqueInput)
  @IsOptional()
  @Field(() => TokenWhereUniqueInput, {
    nullable: true,
  })
  token?: TokenWhereUniqueInput;
}

export { TradeWhereInput as TradeWhereInput };
