/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  BotSchedule as PrismaBotSchedule,
  Trade as PrismaTrade,
} from "@prisma/client";

export class BotScheduleServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.BotScheduleCountArgs, "select">
  ): Promise<number> {
    return this.prisma.botSchedule.count(args);
  }

  async botSchedules(
    args: Prisma.BotScheduleFindManyArgs
  ): Promise<PrismaBotSchedule[]> {
    return this.prisma.botSchedule.findMany(args);
  }
  async botSchedule(
    args: Prisma.BotScheduleFindUniqueArgs
  ): Promise<PrismaBotSchedule | null> {
    return this.prisma.botSchedule.findUnique(args);
  }
  async createBotSchedule(
    args: Prisma.BotScheduleCreateArgs
  ): Promise<PrismaBotSchedule> {
    return this.prisma.botSchedule.create(args);
  }
  async updateBotSchedule(
    args: Prisma.BotScheduleUpdateArgs
  ): Promise<PrismaBotSchedule> {
    return this.prisma.botSchedule.update(args);
  }
  async deleteBotSchedule(
    args: Prisma.BotScheduleDeleteArgs
  ): Promise<PrismaBotSchedule> {
    return this.prisma.botSchedule.delete(args);
  }

  async getTrade(parentId: string): Promise<PrismaTrade | null> {
    return this.prisma.botSchedule
      .findUnique({
        where: { id: parentId },
      })
      .trade();
  }
}
