/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { BotSchedule } from "./BotSchedule";
import { BotScheduleCountArgs } from "./BotScheduleCountArgs";
import { BotScheduleFindManyArgs } from "./BotScheduleFindManyArgs";
import { BotScheduleFindUniqueArgs } from "./BotScheduleFindUniqueArgs";
import { CreateBotScheduleArgs } from "./CreateBotScheduleArgs";
import { UpdateBotScheduleArgs } from "./UpdateBotScheduleArgs";
import { DeleteBotScheduleArgs } from "./DeleteBotScheduleArgs";
import { Trade } from "../../trade/base/Trade";
import { BotScheduleService } from "../botSchedule.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => BotSchedule)
export class BotScheduleResolverBase {
  constructor(
    protected readonly service: BotScheduleService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "BotSchedule",
    action: "read",
    possession: "any",
  })
  async _botSchedulesMeta(
    @graphql.Args() args: BotScheduleCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [BotSchedule])
  @nestAccessControl.UseRoles({
    resource: "BotSchedule",
    action: "read",
    possession: "any",
  })
  async botSchedules(
    @graphql.Args() args: BotScheduleFindManyArgs
  ): Promise<BotSchedule[]> {
    return this.service.botSchedules(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => BotSchedule, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "BotSchedule",
    action: "read",
    possession: "own",
  })
  async botSchedule(
    @graphql.Args() args: BotScheduleFindUniqueArgs
  ): Promise<BotSchedule | null> {
    const result = await this.service.botSchedule(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => BotSchedule)
  @nestAccessControl.UseRoles({
    resource: "BotSchedule",
    action: "create",
    possession: "any",
  })
  async createBotSchedule(
    @graphql.Args() args: CreateBotScheduleArgs
  ): Promise<BotSchedule> {
    return await this.service.createBotSchedule({
      ...args,
      data: {
        ...args.data,

        trade: args.data.trade
          ? {
              connect: args.data.trade,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => BotSchedule)
  @nestAccessControl.UseRoles({
    resource: "BotSchedule",
    action: "update",
    possession: "any",
  })
  async updateBotSchedule(
    @graphql.Args() args: UpdateBotScheduleArgs
  ): Promise<BotSchedule | null> {
    try {
      return await this.service.updateBotSchedule({
        ...args,
        data: {
          ...args.data,

          trade: args.data.trade
            ? {
                connect: args.data.trade,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => BotSchedule)
  @nestAccessControl.UseRoles({
    resource: "BotSchedule",
    action: "delete",
    possession: "any",
  })
  async deleteBotSchedule(
    @graphql.Args() args: DeleteBotScheduleArgs
  ): Promise<BotSchedule | null> {
    try {
      return await this.service.deleteBotSchedule(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Trade, {
    nullable: true,
    name: "trade",
  })
  @nestAccessControl.UseRoles({
    resource: "Trade",
    action: "read",
    possession: "any",
  })
  async getTrade(@graphql.Parent() parent: BotSchedule): Promise<Trade | null> {
    const result = await this.service.getTrade(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
